# -*- coding: utf-8 -*-
"""Desafios semanais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_7gdQeSGF1O0qlCuNW284ibHg75aOnd
"""

vet = []
while i != 0:
    i = int(input("digite um numero"))
    if i % 3 == 0  and i % 5 == 0:
        vet.append("FizzBuzz")
        print(vet)
    elif i % 3 == 0:
        vet.append("Fizz")
        print(vet)
    elif i % 5 == 0:
        vet.append("Buzz")
        print(vet)
    else:
        vet.append(str(i))
        print(vet)